In [2]:
import pandas as pd
import numpy as np

accnt_data = pd.read_csv("sheets/Accounts_Data.csv")
print (accnt_data.head())
cust_data = pd.read_csv("sheets/Customers_Data.csv")
print (cust_data.head())

   account_id  customer_id account_type   open_date   status close_date  \
0        2001         1646      Savings  2024-02-17   Active        NaN
1        2002         1717      Current  2020-09-26   Active        NaN
2        2003         1268      Current  2019-12-18   Active        NaN
3        2004         1358      Savings  2023-10-05   Active        NaN
4        2005         1946       Salary  2016-10-31  Dormant        NaN

  branch_code
0       BR002
1       BR005
2       BR003
3       BR003
4       BR002
   customer_id           name  gender         dob   join_date region  \
0         1001   Gaurav Ghosh    Male  1964-02-16  2016-05-10   East
1         1002     Kiran Khan    Male  1967-12-10  2021-10-31   West
2         1003    Sara Sharma  Female  1977-08-09  2020-11-17   East
3         1004  Zoya Kulkarni  Female  1960-07-18  2019-02-25   East
4         1005   Sonia Pillai  Female  2000-03-16  2019-02-08  South

      occupation
0        Retired
1  Self-Employed
2        Retired
3        Student
4  Self-Employed

In [3]:
df1 = pd.DataFrame({'A': [1, 2], 'B': ['x', 'y']})
df2 = pd.DataFrame({'A': [3, 4], 'B': ['z', 'w']})

In [4]:
top_bottom = pd.concat([df1, df2], axis=0)
side_side = pd.concat([df1, df2], axis=1)

print (top_bottom)
print (side_side)

   A  B
0  1  x
1  2  y
0  3  z
1  4  w
   A  B  A  B
0  1  x  3  z
1  2  y  4  w

In [5]:
print (accnt_data.columns)

Index(['account_id', 'customer_id', 'account_type', 'open_date', 'status',
       'close_date', 'branch_code'],
      dtype='str')

In [6]:
pd.pivot_table(accnt_data, index="account_type", columns="status", aggfunc="count",values="customer_id")

status        Active  Closed  Dormant
account_type
Current          403      41       82
Salary           380      44       80
Savings          362      42       66

In [7]:
print (accnt_data.head())

   account_id  customer_id account_type   open_date   status close_date  \
0        2001         1646      Savings  2024-02-17   Active        NaN
1        2002         1717      Current  2020-09-26   Active        NaN
2        2003         1268      Current  2019-12-18   Active        NaN
3        2004         1358      Savings  2023-10-05   Active        NaN
4        2005         1946       Salary  2016-10-31  Dormant        NaN

  branch_code
0       BR002
1       BR005
2       BR003
3       BR003
4       BR002

In [8]:
gender_by_occupation = cust_data.pivot_table(index="gender",columns="occupation",aggfunc="count",values="customer_id")
print (gender_by_occupation)

occupation  Retired  Salaried  Self-Employed  Student
gender
Female          116       136            133      125
Male            124       119            121      126

In [9]:
gender_by_region = pd.pivot_table(cust_data,index="gender",columns="region",aggfunc="count",values="customer_id")
print(gender_by_region)

region  East  North  South  West
gender
Female   128    128    144   110
Male     114    148    114   114

In [10]:
cust_data.head()

,customer_id,name,gender,dob,join_date,region,occupation
0,1001,Gaurav Ghosh,Male,1964-02-16,2016-05-10,East,Retired
1,1002,Kiran Khan,Male,1967-12-10,2021-10-31,West,Self-Employed
2,1003,Sara Sharma,Female,1977-08-09,2020-11-17,East,Retired
3,1004,Zoya Kulkarni,Female,1960-07-18,2019-02-25,East,Student
4,1005,Sonia Pillai,Female,2000-03-16,2019-02-08,South,Self-Employed

In [11]:
gender_by_occ_reg =pd.pivot_table(cust_data,index=["gender","occupation"],columns="region",aggfunc="count",values="customer_id")

print (gender_by_occ_reg)

region                East  North  South  West
gender occupation
Female Retired          40     24     29    23
       Salaried         21     39     37    39
       Self-Employed    26     41     40    26
       Student          41     24     38    22
Male   Retired          26     33     32    33
       Salaried         31     38     24    26
       Self-Employed    26     37     33    25
       Student          31     40     25    30

In [12]:
no_of_genders = pd.pivot_table (cust_data, index="gender", aggfunc="count",values="customer_id")
print (no_of_genders)

        customer_id
gender
Female          510
Male            490

In [13]:
min_dob = cust_data.groupby("gender")["dob"].min()

In [14]:
import random
cust_data["amount"] = [random.randint(10000,1000000) for i in range(0,1000)]

In [15]:
cust_data.groupby("gender").count()

        customer_id  name  dob  join_date  region  occupation  amount
gender
Female          510   510  510        510     510         510     510
Male            490   490  490        490     490         490     490

In [16]:
cust_data.groupby("gender")["amount"].mean()

gender
Female    518364.962745
Male      501158.857143
Name: amount, dtype: float64

In [17]:
cust_data.groupby("gender")["amount"].max()

gender
Female    999111
Male      998300
Name: amount, dtype: int64

In [18]:
cust_data.groupby("gender")["amount"].sum()

gender
Female    264366131
Male      245567840
Name: amount, dtype: int64

In [19]:
cust_data.groupby("gender")["amount"].min()

gender
Female    15057
Male      15445
Name: amount, dtype: int64

In [20]:
cust_data.groupby("gender")["amount"].describe()

,count,mean,std,min,25%,50%,75%,max
gender,,,,,,,,
Female,510.0,518364.962745,281820.993892,15057.0,287751.25,515187.5,769403.25,999111.0
Male,490.0,501158.857143,290183.108827,15445.0,246084.50,499068.0,751450.00,998300.0

In [21]:
cust_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  1000 non-null   int64
 1   name         1000 non-null   str
 2   gender       1000 non-null   str
 3   dob          1000 non-null   str
 4   join_date    1000 non-null   str
 5   region       1000 non-null   str
 6   occupation   1000 non-null   str
 7   amount       1000 non-null   int64
dtypes: int64(2), str(6)
memory usage: 62.6 KB

In [22]:
d={"customer_id":["count"],
   "dob":["min","max"],
   "join_date":["min","max"],
   "amount":["max","min","mean","median","std","var"]}

In [23]:
cust_data.groupby("gender").agg(d).round(0)

       customer_id         dob               join_date              amount  \
             count         min         max         min         max     max
gender
Female         510  1954-01-22  2006-12-18  2015-09-05  2023-08-20  999111
Male           490  1954-01-16  2006-12-01  2015-09-07  2023-08-14  998300


          min      mean    median       std           var
gender
Female  15057  518365.0  515188.0  281821.0  7.942307e+10
Male    15445  501159.0  499068.0  290183.0  8.420624e+10

In [24]:
pd.set_option('display.float_format','{:.0f}'.format)

In [25]:
cust_data.groupby("gender").agg(d)

       customer_id         dob               join_date              amount  \
             count         min         max         min         max     max
gender
Female         510  1954-01-22  2006-12-18  2015-09-05  2023-08-20  999111
Male           490  1954-01-16  2006-12-01  2015-09-07  2023-08-14  998300


          min   mean median    std         var
gender
Female  15057 518365 515188 281821 79423072598
Male    15445 501159 499068 290183 84206236648

In [26]:
cust_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  1000 non-null   int64
 1   name         1000 non-null   str
 2   gender       1000 non-null   str
 3   dob          1000 non-null   str
 4   join_date    1000 non-null   str
 5   region       1000 non-null   str
 6   occupation   1000 non-null   str
 7   amount       1000 non-null   int64
dtypes: int64(2), str(6)
memory usage: 62.6 KB

In [27]:
cust_data["join_date"]=pd.to_datetime(cust_data["join_date"])

In [28]:
cust_data["join_month"] = cust_data["join_date"].dt.month
cust_data["join_year"] = cust_data["join_date"].dt.year
cust_data["join_day"] = cust_data["join_date"].dt.day

In [29]:
cust_data.groupby("join_year")["customer_id"].count()

join_year
2015     43
2016    142
2017    108
2018    107
2019    138
2020    129
2021    131
2022    114
2023     88
Name: customer_id, dtype: int64

In [30]:
cust_data.set_index("join_date",inplace=True)

In [31]:
cust_data.head()

,customer_id,name,gender,dob,region,occupation,amount,join_month,join_year,join_day
join_date,,,,,,,,,,
2016-05-10,1001,Gaurav Ghosh,Male,1964-02-16,East,Retired,119879,5,2016,10
2021-10-31,1002,Kiran Khan,Male,1967-12-10,West,Self-Employed,278464,10,2021,31
2020-11-17,1003,Sara Sharma,Female,1977-08-09,East,Retired,103314,11,2020,17
2019-02-25,1004,Zoya Kulkarni,Female,1960-07-18,East,Student,276200,2,2019,25
2019-02-08,1005,Sonia Pillai,Female,2000-03-16,South,Self-Employed,382084,2,2019,8

In [32]:
cust_data.sort_index().head()

,customer_id,name,gender,dob,region,occupation,amount,join_month,join_year,join_day
join_date,,,,,,,,,,
2015-09-05,1901,Priya Mukherjee,Female,1978-06-30,North,Salaried,728085,9,2015,5
2015-09-07,1773,Aditi Patel,Male,1987-10-19,West,Student,751451,9,2015,7
2015-09-08,1845,Sara Menon,Female,1967-07-19,South,Salaried,397491,9,2015,8
2015-09-08,1381,Dev Ali,Male,1955-10-28,South,Student,157553,9,2015,8
2015-09-08,1846,Isha Pillai,Male,1974-07-19,East,Self-Employed,931200,9,2015,8

In [33]:
cust_data["dob"] = pd.to_datetime(cust_data["dob"])

In [34]:
cust_data["updated_dob"] = cust_data["dob"] - pd.Timedelta(days=60)

In [35]:
cust_data.head()

,customer_id,name,gender,dob,region,occupation,amount,join_month,join_year,join_day,updated_dob
join_date,,,,,,,,,,,
2016-05-10,1001,Gaurav Ghosh,Male,1964-02-16,East,Retired,119879,5,2016,10,1963-12-18
2021-10-31,1002,Kiran Khan,Male,1967-12-10,West,Self-Employed,278464,10,2021,31,1967-10-11
2020-11-17,1003,Sara Sharma,Female,1977-08-09,East,Retired,103314,11,2020,17,1977-06-10
2019-02-25,1004,Zoya Kulkarni,Female,1960-07-18,East,Student,276200,2,2019,25,1960-05-19
2019-02-08,1005,Sonia Pillai,Female,2000-03-16,South,Self-Employed,382084,2,2019,8,2000-01-16

In [36]:
cust_data["updated_dob2"] = cust_data["dob"]-pd.DateOffset(months=2)

In [37]:
cust_data[["dob","updated_dob2"]]

                  dob updated_dob2
join_date
2016-05-10 1964-02-16   1963-12-16
2021-10-31 1967-12-10   1967-10-10
2020-11-17 1977-08-09   1977-06-09
2019-02-25 1960-07-18   1960-05-18
2019-02-08 2000-03-16   2000-01-16
...               ...          ...
2020-08-25 2006-05-16   2006-03-16
2019-11-08 1977-09-13   1977-07-13
2018-07-12 1954-08-28   1954-06-28
2023-05-03 1992-07-27   1992-05-27
2019-09-29 1992-05-05   1992-03-05

[1000 rows x 2 columns]

In [40]:
pd.date_range(start="2026-02-15",periods=24,freq="h")

DatetimeIndex(['2026-02-15 00:00:00', '2026-02-15 01:00:00',
               '2026-02-15 02:00:00', '2026-02-15 03:00:00',
               '2026-02-15 04:00:00', '2026-02-15 05:00:00',
               '2026-02-15 06:00:00', '2026-02-15 07:00:00',
               '2026-02-15 08:00:00', '2026-02-15 09:00:00',
               '2026-02-15 10:00:00', '2026-02-15 11:00:00',
               '2026-02-15 12:00:00', '2026-02-15 13:00:00',
               '2026-02-15 14:00:00', '2026-02-15 15:00:00',
               '2026-02-15 16:00:00', '2026-02-15 17:00:00',
               '2026-02-15 18:00:00', '2026-02-15 19:00:00',
               '2026-02-15 20:00:00', '2026-02-15 21:00:00',
               '2026-02-15 22:00:00', '2026-02-15 23:00:00'],
              dtype='datetime64[us]', freq='h')

In [41]:
pd.date_range(start="2026-02-15",periods=24,freq="h")+pd.Timedelta(hours=0.5)

DatetimeIndex(['2026-02-15 00:30:00', '2026-02-15 01:30:00',
               '2026-02-15 02:30:00', '2026-02-15 03:30:00',
               '2026-02-15 04:30:00', '2026-02-15 05:30:00',
               '2026-02-15 06:30:00', '2026-02-15 07:30:00',
               '2026-02-15 08:30:00', '2026-02-15 09:30:00',
               '2026-02-15 10:30:00', '2026-02-15 11:30:00',
               '2026-02-15 12:30:00', '2026-02-15 13:30:00',
               '2026-02-15 14:30:00', '2026-02-15 15:30:00',
               '2026-02-15 16:30:00', '2026-02-15 17:30:00',
               '2026-02-15 18:30:00', '2026-02-15 19:30:00',
               '2026-02-15 20:30:00', '2026-02-15 21:30:00',
               '2026-02-15 22:30:00', '2026-02-15 23:30:00'],
              dtype='datetime64[us]', freq='h')