In [12]:
import pandas as pd

In [13]:
print ("hello")

hello

In [14]:
df = pd.read_csv("sheets/day.csv")

In [15]:
df["season"].count()

np.int64(730)

In [16]:
df["season"].unique()

array([1, 2, 3, 4])

In [17]:
df["season"].nunique()

4

In [18]:
df["season"].value_counts()

season
3    188
2    184
1    180
4    178
Name: count, dtype: int64

In [19]:
df.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,01-01-2018,1,0,1,0,1,1,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,02-01-2018,1,0,1,0,2,1,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,03-01-2018,1,0,1,0,3,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,04-01-2018,1,0,1,0,4,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,05-01-2018,1,0,1,0,5,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600

In [20]:
df.nunique()

instant       730
dteday        730
season          4
yr              2
mnth           12
holiday         2
weekday         7
workingday      2
weathersit      3
temp          498
atemp         689
hum           594
windspeed     649
casual        605
registered    678
cnt           695
dtype: int64

In [21]:
df.count()

instant       730
dteday        730
season        730
yr            730
mnth          730
holiday       730
weekday       730
workingday    730
weathersit    730
temp          730
atemp         730
hum           730
windspeed     730
casual        730
registered    730
cnt           730
dtype: int64

In [22]:
df["season"].unique()

array([1, 2, 3, 4])

In [23]:
df.nunique()

instant       730
dteday        730
season          4
yr              2
mnth           12
holiday         2
weekday         7
workingday      2
weathersit      3
temp          498
atemp         689
hum           594
windspeed     649
casual        605
registered    678
cnt           695
dtype: int64

In [24]:
df[df["season"]==2]["season"].count()

np.int64(184)

In [25]:
sub_df=df[["season","temp","hum"]].sample(10)

In [26]:
sub_df.sort_values("temp")

     season       temp      hum
39        1   5.526103  49.4783
25        1   8.917500  86.2500
360       1  13.325000  76.2500
671       4  14.076653  49.1250
107       2  21.012500  54.2500
458       2  22.208347  46.9583
263       3  24.395000  90.0000
166       2  25.761653  68.8333
541       3  25.864153  37.3333
574       3  29.588347  62.3750

In [36]:
df[df["season"]==2].head(5)

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
79,80,21-03-2018,2,0,3,0,3,1,2,17.647835,20.48675,73.7391,19.348461,401,1676,2077
80,81,22-03-2018,2,0,3,0,4,1,1,18.108347,22.03210,62.4583,15.125250,460,2243,2703
81,82,23-03-2018,2,0,3,0,5,1,2,14.225237,16.89695,83.9565,15.695487,203,1918,2121
82,83,24-03-2018,2,0,3,0,6,0,2,11.685000,13.54165,80.5833,16.333729,166,1699,1865
83,84,25-03-2018,2,0,3,0,0,0,1,10.830847,12.81560,49.5000,15.458575,300,1910,2210

In [38]:
sub_df.sort_values("temp",ascending=False)

     season       temp      hum
574       3  29.588347  62.3750
541       3  25.864153  37.3333
166       2  25.761653  68.8333
263       3  24.395000  90.0000
458       2  22.208347  46.9583
107       2  21.012500  54.2500
671       4  14.076653  49.1250
360       1  13.325000  76.2500
25        1   8.917500  86.2500
39        1   5.526103  49.4783

In [39]:
sub_df.sort_values(["season","temp"],ascending=[True,False])

     season       temp      hum
360       1  13.325000  76.2500
25        1   8.917500  86.2500
39        1   5.526103  49.4783
166       2  25.761653  68.8333
458       2  22.208347  46.9583
107       2  21.012500  54.2500
574       3  29.588347  62.3750
541       3  25.864153  37.3333
263       3  24.395000  90.0000
671       4  14.076653  49.1250

In [40]:
sub_df.sort_values(["season","temp"],ascending=[True,False])

     season       temp      hum
360       1  13.325000  76.2500
25        1   8.917500  86.2500
39        1   5.526103  49.4783
166       2  25.761653  68.8333
458       2  22.208347  46.9583
107       2  21.012500  54.2500
574       3  29.588347  62.3750
541       3  25.864153  37.3333
263       3  24.395000  90.0000
671       4  14.076653  49.1250