In [12]:
import pandas as pd

In [13]:
print ("hello")

hello

In [14]:
df = pd.read_csv("sheets/day.csv")

In [15]:
df["season"].count()

np.int64(730)

In [16]:
df["season"].unique()

array([1, 2, 3, 4])

In [17]:
df["season"].nunique()

4

In [18]:
df["season"].value_counts()

season
3    188
2    184
1    180
4    178
Name: count, dtype: int64

In [19]:
df.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,01-01-2018,1,0,1,0,1,1,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,02-01-2018,1,0,1,0,2,1,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,03-01-2018,1,0,1,0,3,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,04-01-2018,1,0,1,0,4,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,05-01-2018,1,0,1,0,5,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600

In [20]:
df.nunique()

instant       730
dteday        730
season          4
yr              2
mnth           12
holiday         2
weekday         7
workingday      2
weathersit      3
temp          498
atemp         689
hum           594
windspeed     649
casual        605
registered    678
cnt           695
dtype: int64

In [21]:
df.count()

instant       730
dteday        730
season        730
yr            730
mnth          730
holiday       730
weekday       730
workingday    730
weathersit    730
temp          730
atemp         730
hum           730
windspeed     730
casual        730
registered    730
cnt           730
dtype: int64

In [22]:
df["season"].unique()

array([1, 2, 3, 4])

In [23]:
df.nunique()

instant       730
dteday        730
season          4
yr              2
mnth           12
holiday         2
weekday         7
workingday      2
weathersit      3
temp          498
atemp         689
hum           594
windspeed     649
casual        605
registered    678
cnt           695
dtype: int64

In [24]:
df[df["season"]==2]["season"].count()

np.int64(184)

In [25]:
sub_df=df[["season","temp","hum"]].sample(10)

In [26]:
sub_df.sort_values("temp")

     season       temp      hum
39        1   5.526103  49.4783
25        1   8.917500  86.2500
360       1  13.325000  76.2500
671       4  14.076653  49.1250
107       2  21.012500  54.2500
458       2  22.208347  46.9583
263       3  24.395000  90.0000
166       2  25.761653  68.8333
541       3  25.864153  37.3333
574       3  29.588347  62.3750

In [36]:
df[df["season"]==2].head(5)

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
79,80,21-03-2018,2,0,3,0,3,1,2,17.647835,20.48675,73.7391,19.348461,401,1676,2077
80,81,22-03-2018,2,0,3,0,4,1,1,18.108347,22.03210,62.4583,15.125250,460,2243,2703
81,82,23-03-2018,2,0,3,0,5,1,2,14.225237,16.89695,83.9565,15.695487,203,1918,2121
82,83,24-03-2018,2,0,3,0,6,0,2,11.685000,13.54165,80.5833,16.333729,166,1699,1865
83,84,25-03-2018,2,0,3,0,0,0,1,10.830847,12.81560,49.5000,15.458575,300,1910,2210

In [38]:
sub_df.sort_values("temp",ascending=False)

     season       temp      hum
574       3  29.588347  62.3750
541       3  25.864153  37.3333
166       2  25.761653  68.8333
263       3  24.395000  90.0000
458       2  22.208347  46.9583
107       2  21.012500  54.2500
671       4  14.076653  49.1250
360       1  13.325000  76.2500
25        1   8.917500  86.2500
39        1   5.526103  49.4783

In [39]:
sub_df.sort_values(["season","temp"],ascending=[True,False])

     season       temp      hum
360       1  13.325000  76.2500
25        1   8.917500  86.2500
39        1   5.526103  49.4783
166       2  25.761653  68.8333
458       2  22.208347  46.9583
107       2  21.012500  54.2500
574       3  29.588347  62.3750
541       3  25.864153  37.3333
263       3  24.395000  90.0000
671       4  14.076653  49.1250

In [40]:
sub_df.sort_values(["season","temp"],ascending=[True,False])

     season       temp      hum
360       1  13.325000  76.2500
25        1   8.917500  86.2500
39        1   5.526103  49.4783
166       2  25.761653  68.8333
458       2  22.208347  46.9583
107       2  21.012500  54.2500
574       3  29.588347  62.3750
541       3  25.864153  37.3333
263       3  24.395000  90.0000
671       4  14.076653  49.1250

In [41]:
for index,i in sub_df.iterrows():
    print (index,i["season"], i["temp"],i["hum"])

263 3.0 24.395 90.0
107 2.0 21.0125 54.25
458 2.0 22.208347 46.9583
39 1.0 5.526103 49.4783
360 1.0 13.325 76.25
541 3.0 25.864153 37.3333
671 4.0 14.076653 49.125
574 3.0 29.588347 62.375
25 1.0 8.9175 86.25
166 2.0 25.761653 68.8333

In [43]:
df.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='str')

In [46]:
for index,i in df.iterrows():
    print (f"index: {index}: values: {i["weathersit"],i["temp"],i["hum"]}")

index: 0: values: (2, 14.110847, 80.5833)
index: 1: values: (2, 14.902598, 69.6087)
index: 2: values: (1, 8.050924, 43.7273)
index: 3: values: (1, 8.2, 59.0435)
index: 4: values: (1, 9.305237, 43.6957)
index: 5: values: (1, 8.378268, 51.8261)
index: 6: values: (2, 8.057402, 49.8696)
index: 7: values: (2, 6.765, 53.5833)
index: 8: values: (1, 5.671653, 43.4167)
index: 9: values: (1, 6.184153, 48.2917)
index: 10: values: (2, 6.932731, 68.6364)
index: 11: values: (1, 7.081807, 59.9545)
index: 12: values: (1, 6.765, 47.0417)
index: 13: values: (1, 6.59567, 53.7826)
index: 14: values: (2, 9.566653, 49.875)
index: 15: values: (1, 9.498347, 48.375)
index: 16: values: (2, 7.209153, 53.75)
index: 17: values: (2, 8.883347, 86.1667)
index: 18: values: (2, 11.979134, 74.1739)
index: 19: values: (2, 10.728347, 53.8333)
index: 20: values: (1, 7.2775, 45.7083)
index: 21: values: (1, 2.4243464, 40.0)
index: 22: values: (1, 3.9573897, 43.6522)
index: 23: values: (1, 3.9930433, 49.1739)
index: 24: values: (2, 9.162598, 61.6957)
index: 25: values: (3, 8.9175, 86.25)
index: 26: values: (1, 7.995, 68.75)
index: 27: values: (2, 8.342598, 79.3043)
index: 28: values: (1, 8.057402, 65.1739)
index: 29: values: (1, 8.877402, 72.2174)
index: 30: values: (2, 7.414153, 60.375)
index: 31: values: (2, 7.879134, 82.9565)
index: 32: values: (2, 10.66, 77.5417)
index: 33: values: (1, 7.665237, 43.7826)
index: 34: values: (2, 8.663464, 58.5217)
index: 35: values: (2, 9.566653, 92.9167)
index: 36: values: (1, 11.719153, 56.8333)
index: 37: values: (1, 11.138347, 73.8333)
index: 38: values: (1, 9.054153, 53.7917)
index: 39: values: (2, 5.526103, 49.4783)
index: 40: values: (1, 5.918268, 43.7391)
index: 41: values: (1, 7.752731, 50.6364)
index: 42: values: (1, 9.1225, 54.4167)
index: 43: values: (1, 12.977402, 45.7391)
index: 44: values: (1, 17.015, 37.5833)
index: 45: values: (1, 10.909567, 31.4348)
index: 46: values: (1, 13.048701, 42.3478)
index: 47: values: (1, 17.869153, 50.5)
index: 48: values: (1, 21.388347, 51.6667)
index: 49: values: (1, 16.365847, 18.7917)
index: 50: values: (1, 11.693897, 40.7826)
index: 51: values: (2, 12.436653, 60.5)
index: 52: values: (1, 7.471102, 57.7778)
index: 53: values: (1, 9.091299, 42.3043)
index: 54: values: (2, 12.121732, 69.7391)
index: 55: values: (2, 14.938268, 71.2174)
index: 56: values: (1, 11.5825, 53.7917)
index: 57: values: (1, 14.082598, 68.0)
index: 58: values: (2, 16.698193, 87.6364)
index: 59: values: (1, 10.933347, 53.5)
index: 60: values: (1, 13.735, 44.9583)
index: 61: values: (1, 8.131653, 31.8333)
index: 62: values: (2, 10.728347, 61.0417)
index: 63: values: (2, 15.750847, 78.9167)
index: 64: values: (2, 15.437402, 94.8261)
index: 65: values: (1, 10.731299, 55.1304)
index: 66: values: (1, 11.9925, 42.0833)
index: 67: values: (2, 12.129153, 77.5417)
index: 68: values: (3, 15.952731, 0.0)
index: 69: values: (2, 12.977402, 64.9565)
index: 70: values: (1, 13.495847, 59.4583)
index: 71: values: (1, 15.758268, 52.7391)
index: 72: values: (1, 13.333897, 49.6957)
index: 73: values: (2, 13.013031, 65.5652)
index: 74: values: (2, 14.973897, 77.6522)
index: 75: values: (1, 17.015, 60.2917)
index: 76: values: (1, 22.14, 52.5217)
index: 77: values: (1, 19.3725, 37.9167)
index: 78: values: (1, 13.6325, 47.375)
index: 79: values: (2, 17.647835, 73.7391)
index: 80: values: (1, 18.108347, 62.4583)
index: 81: values: (2, 14.225237, 83.9565)
index: 82: values: (2, 11.685, 80.5833)
index: 83: values: (1, 10.830847, 49.5)
index: 84: values: (1, 10.899153, 39.4167)
index: 85: values: (2, 10.374763, 49.3913)
index: 86: values: (1, 10.838268, 30.2174)
index: 87: values: (1, 12.4025, 31.4167)
index: 88: values: (2, 12.3, 64.6667)
index: 89: values: (3, 11.001653, 91.8333)
index: 90: values: (2, 12.3, 68.625)
index: 91: values: (2, 12.915, 65.375)
index: 92: values: (1, 15.511653, 48.0)
index: 93: values: (1, 23.506653, 42.625)
index: 94: values: (2, 16.980847, 64.2083)
index: 95: values: (1, 16.024153, 47.0833)
index: 96: values: (1, 17.9375, 60.2917)
index: 97: values: (2, 13.769153, 83.625)
index: 98: values: (2, 14.0425, 87.75)
index: 99: values: (2, 17.493347, 85.75)
index: 100: values: (2, 24.421732, 71.6956)
index: 101: values: (2, 20.6025, 73.9167)
index: 102: values: (2, 16.9125, 81.9167)
index: 103: values: (1, 19.1675, 54.0417)
index: 104: values: (1, 18.313347, 67.125)
index: 105: values: (3, 17.664153, 88.8333)
index: 106: values: (1, 18.723347, 47.9583)
index: 107: values: (1, 21.0125, 54.25)
index: 108: values: (2, 20.739153, 66.5833)
index: 109: values: (1, 24.395, 61.4167)
index: 110: values: (1, 18.825847, 40.7083)
index: 111: values: (2, 13.803347, 72.9583)
index: 112: values: (2, 18.86, 88.7917)
index: 113: values: (2, 23.848347, 81.0833)
index: 114: values: (1, 24.873347, 77.6667)
index: 115: values: (1, 25.898347, 72.9167)
index: 116: values: (2, 25.42, 83.5417)
index: 117: values: (2, 25.3175, 70.0833)
index: 118: values: (1, 20.91, 45.7083)
index: 119: values: (1, 19.3725, 50.3333)
index: 120: values: (2, 18.518347, 76.2083)
index: 121: values: (2, 22.515847, 73.0)
index: 122: values: (2, 25.283347, 69.7083)
index: 123: values: (2, 16.980847, 73.7083)
index: 124: values: (1, 18.825847, 44.4167)
index: 125: values: (1, 19.645847, 59.0)
index: 126: values: (1, 21.32, 54.125)
index: 127: values: (1, 21.661653, 63.1667)
index: 128: values: (1, 21.8325, 58.875)
index: 129: values: (1, 21.8325, 48.9167)
index: 130: values: (1, 22.2425, 63.2917)
index: 131: values: (1, 21.935, 74.75)
index: 132: values: (2, 21.0125, 86.3333)
index: 133: values: (2, 21.354153, 92.25)
index: 134: values: (2, 23.0625, 86.7083)
index: 135: values: (1, 23.6775, 78.7917)
index: 136: values: (2, 23.028347, 83.7917)
index: 137: values: (2, 22.55, 87.0)
index: 138: values: (2, 21.764153, 82.9583)
index: 139: values: (1, 22.003347, 71.9583)
index: 140: values: (1, 24.7025, 62.6667)
index: 141: values: (1, 24.770847, 74.9583)
index: 142: values: (2, 25.898347, 81.0)
index: 143: values: (2, 27.06, 74.0833)
index: 144: values: (1, 27.094153, 69.625)
index: 145: values: (1, 29.041653, 67.75)
index: 146: values: (1, 27.948347, 65.375)
index: 147: values: (1, 26.889153, 72.9583)
index: 148: values: (1, 27.3675, 81.875)
index: 149: values: (1, 30.066653, 68.5)
index: 150: values: (1, 31.775, 63.6667)
index: 151: values: (2, 31.330847, 67.7083)
index: 152: values: (1, 29.315, 30.5)
index: 153: values: (1, 25.42, 35.4167)
index: 154: values: (1, 26.035, 45.625)
index: 155: values: (2, 26.581653, 65.25)
index: 156: values: (1, 27.811653, 60.0)
index: 157: values: (1, 29.0075, 59.7917)
index: 158: values: (1, 31.809153, 62.2083)
index: 159: values: (2, 33.141653, 56.8333)
index: 160: values: (1, 30.955, 60.5)
index: 161: values: (1, 29.725, 65.4583)
index: 162: values: (1, 28.3925, 74.7917)
index: 163: values: (1, 26.035, 49.4583)
index: 164: values: (1, 24.770847, 50.7083)
index: 165: values: (1, 25.693347, 47.1667)
index: 166: values: (2, 25.761653, 68.8333)
index: 167: values: (1, 26.615847, 73.5833)
index: 168: values: (1, 28.563347, 67.0417)
index: 169: values: (2, 28.665847, 66.6667)
index: 170: values: (2, 26.035, 74.625)
index: 171: values: (2, 27.914153, 77.0417)
index: 172: values: (1, 30.066653, 70.75)
index: 173: values: (2, 29.861653, 70.3333)
index: 174: values: (1, 29.690847, 57.3333)
index: 175: values: (1, 28.495, 48.3333)
index: 176: values: (1, 27.88, 51.3333)
index: 177: values: (2, 27.9825, 65.8333)
index: 178: values: (1, 30.510847, 63.4167)
index: 179: values: (1, 29.861653, 49.7917)
index: 180: values: (1, 28.563347, 43.4167)
index: 181: values: (1, 29.6225, 39.625)
index: 182: values: (1, 30.271653, 44.4583)
index: 183: values: (2, 29.383347, 68.25)
index: 184: values: (2, 29.793347, 63.7917)
index: 185: values: (1, 30.613347, 59.0417)
index: 186: values: (1, 29.52, 74.3333)
index: 187: values: (1, 30.75, 65.125)
index: 188: values: (2, 29.075847, 75.7917)
index: 189: values: (1, 30.066653, 60.9167)
index: 190: values: (1, 30.6475, 57.8333)
index: 191: values: (1, 31.2625, 63.5833)
index: 192: values: (1, 32.560847, 55.9167)
index: 193: values: (1, 30.613347, 63.1667)
index: 194: values: (1, 27.914153, 47.625)
index: 195: values: (1, 27.196653, 59.125)
index: 196: values: (1, 28.153347, 58.5)
index: 197: values: (1, 29.485847, 60.4167)
index: 198: values: (1, 30.613347, 65.125)
index: 199: values: (1, 31.843347, 65.0417)
index: 200: values: (1, 31.501653, 70.7083)
index: 201: values: (2, 33.415, 69.125)
index: 202: values: (1, 34.781653, 58.0417)
index: 203: values: (1, 34.815847, 50.0)
index: 204: values: (1, 34.03, 55.0833)
index: 205: values: (1, 30.476653, 75.7083)
index: 206: values: (1, 31.638347, 54.0833)
index: 207: values: (1, 31.775, 40.2917)
index: 208: values: (1, 31.945847, 58.3333)
index: 209: values: (1, 34.371653, 54.25)
index: 210: values: (1, 32.970847, 46.5833)
index: 211: values: (1, 33.039153, 48.0833)
index: 212: values: (1, 31.638347, 55.0833)
index: 213: values: (1, 32.116653, 49.125)
index: 214: values: (2, 29.998347, 65.75)
index: 215: values: (2, 29.11, 75.75)
index: 216: values: (1, 29.144153, 63.0833)
index: 217: values: (2, 29.383347, 75.5)
index: 218: values: (1, 30.4425, 75.2917)
index: 219: values: (1, 31.365, 59.2083)
index: 220: values: (1, 31.775, 57.0417)
index: 221: values: (1, 31.433347, 42.4167)
index: 222: values: (1, 29.4175, 42.375)
index: 223: values: (1, 29.041653, 41.5)
index: 224: values: (2, 28.119153, 72.9583)
index: 225: values: (2, 27.743347, 81.75)
index: 226: values: (1, 27.299153, 71.2083)
index: 227: values: (1, 28.734153, 57.8333)
index: 228: values: (1, 29.656653, 57.5417)
index: 229: values: (1, 29.178347, 65.4583)
index: 230: values: (2, 28.085, 72.2917)
index: 231: values: (1, 28.5975, 67.4167)
index: 232: values: (1, 29.144153, 77.0)
index: 233: values: (1, 28.358347, 47.0)
index: 234: values: (1, 26.274153, 45.5417)
index: 235: values: (1, 27.606653, 60.5)
index: 236: values: (2, 28.050847, 77.1667)
index: 237: values: (1, 28.7, 76.125)
index: 238: values: (2, 27.88, 85.0)
index: 239: values: (1, 28.989419, 56.1765)
index: 240: values: (1, 26.103347, 55.4583)
index: 241: values: (1, 26.205847, 54.8333)
index: 242: values: (1, 26.923347, 59.7917)
index: 243: values: (1, 26.855, 63.9167)
index: 244: values: (2, 26.376653, 72.7083)
index: 245: values: (1, 27.435847, 71.6667)
index: 246: values: (1, 29.075847, 74.2083)
index: 247: values: (2, 27.606653, 79.0417)
index: 248: values: (3, 22.14, 88.6957)
index: 249: values: (3, 24.565847, 91.7083)
index: 250: values: (3, 25.990433, 93.9565)
index: 251: values: (2, 26.65, 89.7917)
index: 252: values: (1, 27.06, 75.375)
index: 253: values: (1, 26.786653, 71.375)
index: 254: values: (1, 26.418268, 69.2174)
index: 255: values: (1, 26.684153, 71.25)
index: 256: values: (1, 27.606653, 69.7083)
index: 257: values: (2, 23.6775, 70.9167)
index: 258: values: (2, 19.235847, 59.0417)
index: 259: values: (2, 20.158347, 71.8333)
index: 260: values: (1, 20.8075, 69.5)
index: 261: values: (2, 22.515847, 69.0)
index: 262: values: (2, 23.028347, 88.125)
index: 263: values: (2, 24.395, 90.0)
index: 264: values: (2, 25.761653, 90.2083)
index: 265: values: (2, 24.975847, 97.25)
index: 266: values: (2, 24.873347, 86.25)
index: 267: values: (2, 26.000847, 84.5)
index: 268: values: (2, 26.615847, 84.8333)
index: 269: values: (2, 26.103347, 88.5417)
index: 270: values: (2, 26.035, 84.875)
index: 271: values: (1, 25.283347, 69.9167)
index: 272: values: (1, 23.130847, 64.75)
index: 273: values: (2, 16.81, 75.375)
index: 274: values: (2, 14.623347, 79.1667)
index: 275: values: (2, 15.750847, 76.0833)
index: 276: values: (1, 19.850847, 71.0)
index: 277: values: (1, 22.071653, 64.7917)
index: 278: values: (1, 20.260847, 62.0833)
index: 279: values: (1, 20.944153, 68.4167)
index: 280: values: (1, 21.388347, 70.125)
index: 281: values: (1, 22.174153, 72.75)
index: 282: values: (1, 23.404153, 73.375)
index: 283: values: (2, 23.233347, 80.875)
index: 284: values: (3, 22.276653, 90.625)
index: 285: values: (2, 24.155847, 89.6667)
index: 286: values: (2, 22.584153, 71.625)
index: 287: values: (1, 20.773347, 48.3333)
index: 288: values: (1, 20.978347, 48.6667)
index: 289: values: (1, 21.900847, 57.9583)
index: 290: values: (2, 21.8325, 70.1667)
index: 291: values: (3, 22.211299, 89.5217)
index: 292: values: (1, 19.509153, 63.625)
index: 293: values: (1, 17.5275, 57.4167)
index: 294: values: (1, 17.3225, 62.9167)
index: 295: values: (1, 17.288347, 74.125)
index: 296: values: (1, 18.996653, 77.2083)
index: 297: values: (1, 19.338347, 62.2917)
index: 298: values: (2, 19.850847, 72.0417)
index: 299: values: (2, 19.27, 81.2917)
index: 300: values: (2, 13.564153, 58.5833)
index: 301: values: (3, 10.420847, 88.25)
index: 302: values: (1, 13.085847, 62.375)
index: 303: values: (1, 13.94, 70.3333)
index: 304: values: (1, 16.434153, 68.375)
index: 305: values: (1, 15.4775, 71.875)
index: 306: values: (1, 16.741653, 70.2083)
index: 307: values: (2, 16.536653, 62.25)
index: 308: values: (1, 13.393347, 51.9167)
index: 309: values: (1, 14.281653, 73.4583)
index: 310: values: (1, 16.195, 75.875)
index: 311: values: (1, 16.741653, 72.1667)
index: 312: values: (1, 16.4, 75.8333)
index: 313: values: (2, 15.58, 81.3333)
index: 314: values: (1, 13.290847, 44.625)
index: 315: values: (1, 14.623347, 55.2917)
index: 316: values: (1, 18.074153, 45.8333)
index: 317: values: (1, 21.73, 58.7083)
index: 318: values: (2, 21.73, 68.875)
index: 319: values: (3, 18.723347, 93.0)
index: 320: values: (2, 14.008347, 57.5833)
index: 321: values: (1, 11.240847, 41.0)
index: 322: values: (1, 13.495847, 50.2083)
index: 323: values: (2, 18.996653, 68.4583)
index: 324: values: (3, 18.3475, 91.0)
index: 325: values: (3, 17.083347, 96.25)
index: 326: values: (2, 18.074153, 75.7917)
index: 327: values: (1, 15.306653, 54.9167)
index: 328: values: (1, 15.375, 64.375)
index: 329: values: (1, 15.409153, 68.1667)
index: 330: values: (1, 18.825847, 69.8333)
index: 331: values: (1, 20.642598, 74.3043)
index: 332: values: (2, 18.791653, 83.0833)
index: 333: values: (1, 13.325, 61.3333)
index: 334: values: (1, 12.8125, 52.4583)
index: 335: values: (1, 12.880847, 62.5833)
index: 336: values: (1, 12.265847, 61.2917)
index: 337: values: (1, 13.564153, 77.5833)
index: 338: values: (2, 15.819153, 82.7083)
index: 339: values: (3, 18.9625, 94.9583)
index: 340: values: (3, 16.81, 97.0417)
index: 341: values: (1, 10.899153, 58.0)
index: 342: values: (1, 11.924153, 69.5833)
index: 343: values: (1, 11.275, 50.75)
index: 344: values: (1, 9.054153, 49.0)
index: 345: values: (1, 9.771653, 67.0833)
index: 346: values: (1, 11.5825, 59.0)
index: 347: values: (2, 13.0175, 66.375)
index: 348: values: (2, 17.3225, 63.4167)
index: 349: values: (2, 15.375, 50.0417)
index: 350: values: (2, 10.591653, 56.0833)
index: 351: values: (1, 9.771653, 58.625)
index: 352: values: (1, 11.343347, 63.75)
index: 353: values: (2, 15.819153, 59.5417)
index: 354: values: (2, 17.561653, 85.8333)
index: 355: values: (2, 17.356653, 75.75)
index: 356: values: (1, 15.306653, 68.625)
index: 357: values: (1, 12.4025, 54.25)
index: 358: values: (1, 11.266103, 68.1304)
index: 359: values: (1, 13.191299, 50.6957)
index: 360: values: (2, 13.325, 76.25)
index: 361: values: (1, 12.26433, 50.3913)
index: 362: values: (1, 10.181653, 57.4167)
index: 363: values: (1, 12.778347, 63.6667)
index: 364: values: (1, 16.81, 61.5833)
index: 365: values: (1, 15.17, 69.25)
index: 366: values: (1, 11.194763, 38.1304)
index: 367: values: (1, 6.15, 44.125)
index: 368: values: (2, 4.4075, 41.4583)
index: 369: values: (1, 10.899153, 52.4167)
index: 370: values: (1, 13.700847, 54.2083)
index: 371: values: (1, 16.126653, 53.1667)
index: 372: values: (1, 13.8375, 46.5)
index: 373: values: (2, 9.190847, 70.1667)
index: 374: values: (1, 12.656536, 64.6522)
index: 375: values: (2, 11.240847, 84.75)
index: 376: values: (2, 15.6825, 80.2917)
index: 377: values: (1, 11.240847, 50.75)
index: 378: values: (1, 7.38, 45.75)
index: 379: values: (1, 6.833347, 41.9167)
index: 380: values: (1, 7.79, 52.25)
index: 381: values: (2, 15.294763, 71.6087)
index: 382: values: (1, 12.436653, 44.3333)
index: 383: values: (1, 7.79, 49.75)
index: 384: values: (2, 8.9175, 45.0)
index: 385: values: (2, 7.106653, 83.125)
index: 386: values: (2, 6.6625, 79.625)
index: 387: values: (2, 8.951653, 91.125)
index: 388: values: (1, 14.0425, 83.5833)
index: 389: values: (1, 12.060847, 64.375)
index: 390: values: (2, 14.008347, 76.9583)
index: 391: values: (2, 17.425, 74.125)
index: 392: values: (1, 12.949153, 54.3333)
index: 393: values: (1, 11.5825, 31.125)
index: 394: values: (1, 11.035847, 40.0833)
index: 395: values: (1, 15.99, 41.6667)
index: 396: values: (1, 19.235847, 50.7917)
index: 397: values: (2, 16.365847, 67.2917)
index: 398: values: (1, 12.846653, 52.6667)
index: 399: values: (2, 10.830847, 77.9583)
index: 400: values: (2, 10.899153, 68.7917)
index: 401: values: (1, 11.586969, 62.2174)
index: 402: values: (1, 14.520847, 49.625)
index: 403: values: (2, 10.523347, 72.2917)
index: 404: values: (1, 10.865, 56.2083)
index: 405: values: (2, 11.514153, 54.0)
index: 406: values: (3, 9.190847, 73.125)
index: 407: values: (1, 5.2275, 46.4583)
index: 408: values: (1, 9.1225, 41.125)
index: 409: values: (2, 13.085847, 50.875)
index: 410: values: (1, 14.281653, 53.125)
index: 411: values: (2, 12.983347, 75.2917)
index: 412: values: (1, 14.076653, 63.4583)
index: 413: values: (1, 14.213347, 53.4583)
index: 414: values: (2, 11.48, 51.5833)
index: 415: values: (1, 11.48, 50.7826)
index: 416: values: (1, 11.800866, 59.4348)
index: 417: values: (1, 16.229153, 56.7917)
index: 418: values: (1, 18.620847, 55.4583)
index: 419: values: (2, 16.7075, 73.75)
index: 420: values: (1, 11.924153, 39.5833)
index: 421: values: (1, 11.445847, 41.0)
index: 422: values: (1, 15.033347, 49.0833)
index: 423: values: (1, 14.725847, 39.5833)
index: 424: values: (1, 19.919153, 61.5417)
index: 425: values: (2, 14.486653, 65.7083)
index: 426: values: (2, 16.980847, 62.125)
index: 427: values: (1, 13.359153, 40.3333)
index: 428: values: (1, 9.976653, 50.625)
index: 429: values: (1, 10.591653, 45.6667)
index: 430: values: (1, 16.570847, 51.3333)
index: 431: values: (1, 21.6275, 56.75)
index: 432: values: (2, 16.844153, 40.7083)
index: 433: values: (1, 11.7875, 35.0417)
index: 434: values: (1, 14.831299, 47.6957)
index: 435: values: (1, 19.133347, 48.9167)
index: 436: values: (1, 23.165, 61.75)
index: 437: values: (1, 23.4725, 50.7083)
index: 438: values: (1, 22.8575, 57.9583)
index: 439: values: (2, 17.869153, 84.2083)
index: 440: values: (2, 21.080847, 75.5833)
index: 441: values: (2, 19.3725, 81.0)
index: 442: values: (1, 22.345, 72.875)
index: 443: values: (1, 22.994153, 80.7917)
index: 444: values: (2, 21.798347, 82.125)
index: 445: values: (1, 22.720847, 83.125)
index: 446: values: (2, 24.668347, 69.4167)
index: 447: values: (2, 20.6025, 88.5417)
index: 448: values: (2, 17.9375, 88.0833)
index: 449: values: (1, 18.279153, 47.7917)
index: 450: values: (1, 13.256653, 29.0)
index: 451: values: (1, 19.850847, 48.125)
index: 452: values: (1, 20.260847, 43.9167)
index: 453: values: (2, 15.17, 58.0833)
index: 454: values: (2, 17.390847, 73.8333)
index: 455: values: (2, 17.459153, 67.625)
index: 456: values: (1, 17.790433, 50.4348)
index: 457: values: (1, 19.133347, 39.6667)
index: 458: values: (1, 22.208347, 46.9583)
index: 459: values: (1, 17.835, 37.4167)
index: 460: values: (1, 16.536653, 37.7083)
index: 461: values: (1, 17.9375, 25.4167)
index: 462: values: (1, 20.5, 27.5833)
index: 463: values: (1, 20.055847, 31.75)
index: 464: values: (1, 18.313347, 43.5)
index: 465: values: (1, 14.296536, 46.9565)
index: 466: values: (1, 16.2975, 46.625)
index: 467: values: (1, 18.1425, 40.8333)
index: 468: values: (1, 20.295, 50.2917)
index: 469: values: (1, 24.873347, 50.7917)
index: 470: values: (1, 27.230847, 56.1667)
index: 471: values: (1, 24.941653, 39.0417)
index: 472: values: (2, 18.996653, 56.9167)
index: 473: values: (1, 20.431653, 61.25)

In [48]:
df["weekday"].unique()

array([1, 2, 3, 4, 5, 6, 0])

In [52]:
def week_map(value):
    d={1:"Monday",2:"Tuesday",3:"Wednesday",4:"Thursday",5:"Friday",6:"Saturday",0:"Sunday"}
    return d[value]

In [53]:
df["weekday_mod"]=df["weekday"].apply(week_map)

In [54]:
df["weekday_mod"]

0         Monday
1        Tuesday
2      Wednesday
3       Thursday
4         Friday
         ...
725       Friday
726     Saturday
727       Sunday
728       Monday
729      Tuesday
Name: weekday_mod, Length: 730, dtype: str

In [55]:
df["weekday_mod"].str.upper()

0         MONDAY
1        TUESDAY
2      WEDNESDAY
3       THURSDAY
4         FRIDAY
         ...
725       FRIDAY
726     SATURDAY
727       SUNDAY
728       MONDAY
729      TUESDAY
Name: weekday_mod, Length: 730, dtype: str

In [56]:
df["weekday_mod"].str.lower()

0         monday
1        tuesday
2      wednesday
3       thursday
4         friday
         ...
725       friday
726     saturday
727       sunday
728       monday
729      tuesday
Name: weekday_mod, Length: 730, dtype: str

In [57]:
df["weekday_mod"].str.title()

0         Monday
1        Tuesday
2      Wednesday
3       Thursday
4         Friday
         ...
725       Friday
726     Saturday
727       Sunday
728       Monday
729      Tuesday
Name: weekday_mod, Length: 730, dtype: str

In [58]:
df["weekday_mod"].str.len()

0      6
1      7
2      9
3      8
4      6
      ..
725    6
726    8
727    6
728    6
729    7
Name: weekday_mod, Length: 730, dtype: int64

In [59]:
df["weekday_mod"].str.replace("M","Q")

0         Qonday
1        Tuesday
2      Wednesday
3       Thursday
4         Friday
         ...
725       Friday
726     Saturday
727       Sunday
728       Qonday
729      Tuesday
Name: weekday_mod, Length: 730, dtype: str

In [64]:
pd.get_option("display.max_rows")

60

In [68]:
pd.set_option("display.max_columns",5)

In [69]:
df.head()

   instant      dteday  ...   cnt  weekday_mod
0        1  01-01-2018  ...   985       Monday
1        2  02-01-2018  ...   801      Tuesday
2        3  03-01-2018  ...  1349    Wednesday
3        4  04-01-2018  ...  1562     Thursday
4        5  05-01-2018  ...  1600       Friday

[5 rows x 17 columns]

In [73]:
pd.set_option("display.max_rows",10)

In [75]:
pd.reset_option("all")

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_46816\3365680546.py:1: Pandas4Warning: 'future.no_silent_downcasting' is deprecated, please refrain from using it.
  pd.reset_option("all")
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_46816\3365680546.py:1: Pandas4Warning: The 'mode.copy_on_write' option is deprecated. Copy-on-Write can no longer be disabled (it is always enabled with pandas >= 3.0), and setting the option has no impact. This option will be removed in pandas 4.0.
  pd.reset_option("all")

In [ ]:
pd.set_option("display")

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt,weekday_mod
0,1,01-01-2018,1,0,1,0,1,1,2,14.110847,18.18125,80.5833,10.749882,331,654,985,Monday
1,2,02-01-2018,1,0,1,0,2,1,2,14.902598,17.68695,69.6087,16.652113,131,670,801,Tuesday
2,3,03-01-2018,1,0,1,0,3,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349,Wednesday
3,4,04-01-2018,1,0,1,0,4,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562,Thursday
4,5,05-01-2018,1,0,1,0,5,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600,Friday

In [80]:
pd.set_option("display.max_columns", 5)

In [ ]:
df.head()

   instant      dteday  ...   cnt  weekday_mod
4        5  05-01-2018  ...  1600       Friday

[1 rows x 17 columns]

In [81]:
pd.reset_option("all")

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_46816\3365680546.py:1: Pandas4Warning: 'future.no_silent_downcasting' is deprecated, please refrain from using it.
  pd.reset_option("all")
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_46816\3365680546.py:1: Pandas4Warning: The 'mode.copy_on_write' option is deprecated. Copy-on-Write can no longer be disabled (it is always enabled with pandas >= 3.0), and setting the option has no impact. This option will be removed in pandas 4.0.
  pd.reset_option("all")

In [82]:
df.isnull().sum()

instant        0
dteday         0
season         0
yr             0
mnth           0
holiday        0
weekday        0
workingday     0
weathersit     0
temp           0
atemp          0
hum            0
windspeed      0
casual         0
registered     0
cnt            0
weekday_mod    0
dtype: int64

In [83]:
df.isnull().sum()

instant        0
dteday         0
season         0
yr             0
mnth           0
holiday        0
weekday        0
workingday     0
weathersit     0
temp           0
atemp          0
hum            0
windspeed      0
casual         0
registered     0
cnt            0
weekday_mod    0
dtype: int64

In [84]:
100*df.isna().mean()

instant        0.0
dteday         0.0
season         0.0
yr             0.0
mnth           0.0
holiday        0.0
weekday        0.0
workingday     0.0
weathersit     0.0
temp           0.0
atemp          0.0
hum            0.0
windspeed      0.0
casual         0.0
registered     0.0
cnt            0.0
weekday_mod    0.0
dtype: float64

In [88]:
import numpy as np
import pandas as pd
data = {
    'Patient_ID': ['P001', 'P002', 'P003', 'P004', 'P005'],
    'Heart_Rate (bpm)': [78, np.nan, 85, 72, 90],
    'Blood_Pressure (mmHg)': ['120/80', '118/76', np.nan, '110/70', '130/85'],
    'Temperature (°C)': [36.8, 37.2, 38.0, np.nan, 37.5],
    'Oxygen_Saturation (%)': [98, 96, 94, 97, np.nan]
}

df = pd.DataFrame(data)
df.isnull().sum()
100*df.isna().mean()

Patient_ID                0.0
Heart_Rate (bpm)         20.0
Blood_Pressure (mmHg)    20.0
Temperature (°C)         20.0
Oxygen_Saturation (%)    20.0
dtype: float64

In [93]:
#ignore the columns which have more than 50% missing values
#otherwise we impute
#median is preferred when compared with mean because mean is affected by outliers but median is not affected by outliers

heart_rate_mean = df['Heart_Rate (bpm)'].mean()
print(heart_rate_mean)

81.25

In [94]:
df['Heart_Rate (bpm)'] = df['Heart_Rate (bpm)'].fillna(heart_rate_mean)

In [95]:
df['Heart_Rate (bpm)']

0    78.00
1    81.25
2    85.00
3    72.00
4    90.00
Name: Heart_Rate (bpm), dtype: float64

In [96]:
temp_median = df['Temperature (°C)'].median()
print(temp_median)
df['Temperature (°C)'] = df['Temperature (°C)'].fillna(temp_median)

37.35

In [97]:
df['Temperature (°C)']

0    36.80
1    37.20
2    38.00
3    37.35
4    37.50
Name: Temperature (°C), dtype: float64

In [98]:
df.drop_duplicates()

,Patient_ID,Heart_Rate (bpm),Blood_Pressure (mmHg),Temperature (°C),Oxygen_Saturation (%)
0,P001,78.00,120/80,36.80,98.0
1,P002,81.25,118/76,37.20,96.0
2,P003,85.00,NaN,38.00,94.0
3,P004,72.00,110/70,37.35,97.0
4,P005,90.00,130/85,37.50,NaN

In [99]:
df.drop_duplicates(subset=["Patient_ID"])

,Patient_ID,Heart_Rate (bpm),Blood_Pressure (mmHg),Temperature (°C),Oxygen_Saturation (%)
0,P001,78.00,120/80,36.80,98.0
1,P002,81.25,118/76,37.20,96.0
2,P003,85.00,NaN,38.00,94.0
3,P004,72.00,110/70,37.35,97.0
4,P005,90.00,130/85,37.50,NaN

In [100]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool