In [ ]:
#apply function works when you want to apply logic to rows
#multiple rows can be updated at the same time.

In [1]:
import pandas as pd

In [2]:
Region_A = pd.Series ([100,200,132,40,5], index=["Jan","Feb","Mar","Apr","May"])
Region_B = pd.Series ([60,7,88,99,150], index=["Jan","Feb","Mar","Apr","May"])

In [3]:
def sales_category(sales):
    if sales < 100:
        return "Low"
    elif sales < 5000:
        return "Medium"
    else:
        return "High"
    
tagged_region_A = Region_A.apply(sales_category)
print (tagged_region_A)

Jan    Medium
Feb    Medium
Mar    Medium
Apr       Low
May       Low
dtype: str

Dataframes

array data structure of numpy 
series is data structure of pandas
dataframe is structure of pandas

In [4]:
# Create a sample DataFrame with Name, Age, and City columns
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Henry', 'Iris', 'Jack'],
    'Age': [25, 30, 35, 28, 32, 27, 29, 31, 26, 33],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose']
}

In [5]:
df = pd.DataFrame(data)
print(df)

      Name  Age          City
0    Alice   25      New York
1      Bob   30   Los Angeles
2  Charlie   35       Chicago
3    David   28       Houston
4      Eve   32       Phoenix
5    Frank   27  Philadelphia
6    Grace   29   San Antonio
7    Henry   31     San Diego
8     Iris   26        Dallas
9     Jack   33      San Jose

In [ ]:
import pandas as pd

# Create a sample DataFrame with Name, Age, and City columns
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Henry', 'Iris', 'Jack'],
    'Age': [25, 30, 35, 28, 32, 27, 29, 31, 26, 33],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose']
}

df = pd.DataFrame(data)
print (df)

In [ ]:
ls = [['Amit', 25, 'Delhi']]
print (ls)

In [ ]:
import subprocess
subprocess.check_call(['pip', 'install', 'pandas'])

In [ ]:
ls = [['Amit', 25, 'Delhi']]
print (ls)

In [ ]:
import sys
print(sys.executable)

In [6]:
data = {
    'Name': ['Amit', 'Neha', 'Ravi', 'Simran'],
    'Age': [25, 28, 22, 26],
    'City': ['Delhi', 'Mumbai', 'Pune', 'Chennai']
}
ls=[['Amit',25,'Delhi'],['Neha',28,'Mumbai'],['Ravi',22,'Pune'],['Simran',26,'Chennai']]
df=pd.DataFrame(ls,columns=["Name","Age","City"],index=["S1","S2","S3","S4"])
df

      Name  Age     City
S1    Amit   25    Delhi
S2    Neha   28   Mumbai
S3    Ravi   22     Pune
S4  Simran   26  Chennai

In [10]:
df.to_excel("students.xlsx", index=False)
df.to_csv("students.csv", index=False)

In [11]:
df.to_excel(r"sheets/students.xlsx", index=False)

In [17]:
data = pd.read_csv(r"sheets/air_quality_data.csv")
data

          City  PM2.5  PM10  NO2   CO
0        Delhi    250   300   40  1.1
1      Beijing    180   220   60  1.3
2  Los Angeles     90   110   30  0.7
3        Paris     60    80   25  0.6
4       Sydney     40    55   20  0.4

In [18]:
data.head()

          City  PM2.5  PM10  NO2   CO
0        Delhi    250   300   40  1.1
1      Beijing    180   220   60  1.3
2  Los Angeles     90   110   30  0.7
3        Paris     60    80   25  0.6
4       Sydney     40    55   20  0.4

In [19]:
data.shape

(5, 5)

In [20]:
data.columns

Index(['City', 'PM2.5', 'PM10', 'NO2', 'CO'], dtype='str')

In [21]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   City    5 non-null      str
 1   PM2.5   5 non-null      int64
 2   PM10    5 non-null      int64
 3   NO2     5 non-null      int64
 4   CO      5 non-null      float64
dtypes: float64(1), int64(3), str(1)
memory usage: 332.0 bytes

In [22]:
data.info

<bound method DataFrame.info of           City  PM2.5  PM10  NO2   CO
0        Delhi    250   300   40  1.1
1      Beijing    180   220   60  1.3
2  Los Angeles     90   110   30  0.7
3        Paris     60    80   25  0.6
4       Sydney     40    55   20  0.4>

In [23]:
data.describe()

            PM2.5        PM10        NO2        CO
count    5.000000    5.000000   5.000000  5.000000
mean   124.000000  153.000000  35.000000  0.820000
std     88.487287  103.537433  15.811388  0.370135
min     40.000000   55.000000  20.000000  0.400000
25%     60.000000   80.000000  25.000000  0.600000
50%     90.000000  110.000000  30.000000  0.700000
75%    180.000000  220.000000  40.000000  1.100000
max    250.000000  300.000000  60.000000  1.300000

In [25]:
data.describe(include='all')

         City       PM2.5        PM10        NO2        CO
count       5    5.000000    5.000000   5.000000  5.000000
unique      5         NaN         NaN        NaN       NaN
top     Delhi         NaN         NaN        NaN       NaN
freq        1         NaN         NaN        NaN       NaN
mean      NaN  124.000000  153.000000  35.000000  0.820000
std       NaN   88.487287  103.537433  15.811388  0.370135
min       NaN   40.000000   55.000000  20.000000  0.400000
25%       NaN   60.000000   80.000000  25.000000  0.600000
50%       NaN   90.000000  110.000000  30.000000  0.700000
75%       NaN  180.000000  220.000000  40.000000  1.100000
max       NaN  250.000000  300.000000  60.000000  1.300000

Indexing

In [26]:
data.head()

          City  PM2.5  PM10  NO2   CO
0        Delhi    250   300   40  1.1
1      Beijing    180   220   60  1.3
2  Los Angeles     90   110   30  0.7
3        Paris     60    80   25  0.6
4       Sydney     40    55   20  0.4

In [29]:
data[["City","PM10","CO"]]

          City  PM10   CO
0        Delhi   300  1.1
1      Beijing   220  1.3
2  Los Angeles   110  0.7
3        Paris    80  0.6
4       Sydney    55  0.4

In [30]:
data.loc[0:1,"City"]

0      Delhi
1    Beijing
Name: City, dtype: str

In [32]:
#loc is allowing you to find combinations of rows and columns.
data.loc[0:5,["City","PM10","CO"]]

          City  PM10   CO
0        Delhi   300  1.1
1      Beijing   220  1.3
2  Los Angeles   110  0.7
3        Paris    80  0.6
4       Sydney    55  0.4

In [33]:
df.head()

      Name  Age     City
S1    Amit   25    Delhi
S2    Neha   28   Mumbai
S3    Ravi   22     Pune
S4  Simran   26  Chennai

In [37]:
df.loc[S1:S4,["Name","City"]]

NameError: name 'S1' is not defined

In [41]:
data.set_index("City")

             PM2.5  PM10  NO2   CO
City
Delhi          250   300   40  1.1
Beijing        180   220   60  1.3
Los Angeles     90   110   30  0.7
Paris           60    80   25  0.6
Sydney          40    55   20  0.4

In [40]:
data

          City  PM2.5  PM10  NO2   CO
0        Delhi    250   300   40  1.1
1      Beijing    180   220   60  1.3
2  Los Angeles     90   110   30  0.7
3        Paris     60    80   25  0.6
4       Sydney     40    55   20  0.4

In [44]:
data.set_index("City",inplace=True)

KeyError: "None of ['City'] are in the columns"

In [45]:
data.head()

             PM2.5  PM10  NO2   CO
City
Delhi          250   300   40  1.1
Beijing        180   220   60  1.3
Los Angeles     90   110   30  0.7
Paris           60    80   25  0.6
Sydney          40    55   20  0.4

In [46]:
data.set_index("City",inplace=True)

KeyError: "None of ['City'] are in the columns"

In [47]:
data.columns

Index(['PM2.5', 'PM10', 'NO2', 'CO'], dtype='str')

In [48]:
data.head()

             PM2.5  PM10  NO2   CO
City
Delhi          250   300   40  1.1
Beijing        180   220   60  1.3
Los Angeles     90   110   30  0.7
Paris           60    80   25  0.6
Sydney          40    55   20  0.4

In [51]:
#label based indexing
data.loc["Delhi",["PM2.5","PM10"]]

PM2.5    250
PM10     300
Name: Delhi, dtype: int64

In [54]:
#position based indexing
data.iloc[0:2,1:3]

         PM10  NO2
City
Delhi     300   40
Beijing   220   60

In [56]:
#position based indexing, complicated way of handling 
data.iloc[0:2][["PM2.5","PM10"]]

         PM2.5  PM10
City
Delhi      250   300
Beijing    180   220

In [57]:
data = {
    'Employee_ID': ['E1001', 'E1002', 'E1003', 'E1004', 'E1005',
                    'E1006', 'E1007', 'E1008', 'E1009', 'E1010'],
    'Name': ['Amit', 'Neha', 'Ravi', 'Simran', 'Karan',
             'Priya', 'Raj', 'Anita', 'Vivek', 'Meena'],
    'Department': ['Sales', 'HR', 'IT', 'Finance', 'Marketing',
                   'HR', 'IT', 'Sales', 'Finance', 'Marketing'],
    'Age': [28, 32, 26, 41, 35, 30, 27, 29, 38, 33],
    'Experience_Years': [3, 8, 2, 15, 10, 6, 4, 5, 12, 9],
    'Monthly_Salary': [40000, 55000, 35000, 90000, 75000,
                       60000, 42000, 48000, 85000, 72000]
}
df = pd.DataFrame(data)
df

  Employee_ID    Name Department  Age  Experience_Years  Monthly_Salary
0       E1001    Amit      Sales   28                 3           40000
1       E1002    Neha         HR   32                 8           55000
2       E1003    Ravi         IT   26                 2           35000
3       E1004  Simran    Finance   41                15           90000
4       E1005   Karan  Marketing   35                10           75000
5       E1006   Priya         HR   30                 6           60000
6       E1007     Raj         IT   27                 4           42000
7       E1008   Anita      Sales   29                 5           48000
8       E1009   Vivek    Finance   38                12           85000
9       E1010   Meena  Marketing   33                 9           72000

In [58]:
df[(df["Monthly_Salary"]>=40000) & (df["Monthly_Salary"]<=60000)][["Employee_ID","Department"]]

  Employee_ID Department
0       E1001      Sales
1       E1002         HR
5       E1006         HR
6       E1007         IT
7       E1008      Sales

In [59]:
df.query("Monthly_Salary >= 40000 and Monthly_Salary <= 60000")[["Employee_ID","Department"]]

  Employee_ID Department
0       E1001      Sales
1       E1002         HR
5       E1006         HR
6       E1007         IT
7       E1008      Sales

In [60]:
df.query("Department == 'HR'" or "Deparment=='Sales")

  Employee_ID   Name Department  Age  Experience_Years  Monthly_Salary
1       E1002   Neha         HR   32                 8           55000
5       E1006  Priya         HR   30                 6           60000

In [68]:
df[(df["Department"] == "HR") | (df["Department"] == "Sales")]

  Employee_ID   Name Department  Age  Experience_Years  Monthly_Salary
0       E1001   Amit      Sales   28                 3           40000
1       E1002   Neha         HR   32                 8           55000
5       E1006  Priya         HR   30                 6           60000
7       E1008  Anita      Sales   29                 5           48000

In [69]:
df[df["Department"].isin(["HR","Sales"])]

  Employee_ID   Name Department  Age  Experience_Years  Monthly_Salary
0       E1001   Amit      Sales   28                 3           40000
1       E1002   Neha         HR   32                 8           55000
5       E1006  Priya         HR   30                 6           60000
7       E1008  Anita      Sales   29                 5           48000

In [70]:
df[df["Monthly_Salary"].ge(50000)]

  Employee_ID    Name Department  Age  Experience_Years  Monthly_Salary
1       E1002    Neha         HR   32                 8           55000
3       E1004  Simran    Finance   41                15           90000
4       E1005   Karan  Marketing   35                10           75000
5       E1006   Priya         HR   30                 6           60000
8       E1009   Vivek    Finance   38                12           85000
9       E1010   Meena  Marketing   33                 9           72000

In [76]:
df.head()

  Employee_ID    Name Department  Age  Experience_Years  Monthly_Salary
0       E1001    Amit      Sales   28                 3           40000
1       E1002    Neha         HR   32                 8           55000
2       E1003    Ravi         IT   26                 2           35000
3       E1004  Simran    Finance   41                15           90000
4       E1005   Karan  Marketing   35                10           75000

In [ ]:
which python

In [ ]:
which python

In [ ]:
data = {
    "EmpID":   [101, 102, 103, 104, 105, 106, 107, 108],
    "Name":    ["Asha", "Ravi", "Meena", "Kiran", "Suman", "Arjun", "Neha", "Irfan"],
    "Dept":    ["IT", "Sales", "Sales", "HR", "IT", "Finance", "IT", "HR"],
    "City":    ["Delhi", "Mumbai", "Delhi", "Pune", "Chennai", "Mumbai", "Delhi", "Pune"],
    "Salary":  [65000, 52000, 58000, 48000, 72000, 83000, 61000, 50000],
    "Rating":  [4.2, 3.6, 4.0, 3.2, 4.7, 4.4, 3.9, 3.5],
    "Joined":  pd.to_datetime(["2023-04-10","2022-11-05","2023-01-15","2021-07-22","2020-02-01","2019-09-18","2023-06-30","2022-03-12"]),
    "Active":  [True, True, True, False, True, True, False, True]
}
df = pd.DataFrame(data)

In [ ]:
which python

In [ ]:
which python

In [ ]:
print ("hello world")

In [ ]:
import sys
print(sys.executable)